version: '3.8'

services:
  frontend:
    image: mariadaw/vue-app:latest
    ports:
      - "5173:5173"
    working_dir: /app
    networks:
      - echonetnet

  backend:
    image: mariadaw/django-api:latest
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:dFSjarqIywDKddBfhtuTGAiaurpcgbXj@switchback.proxy.rlwy.net:58387/railway
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - echonetnet

networks:
  echonetnet: