FROM node:20-buster


ENV NODE_OPTIONS=--no-warnings

RUN adduser --disabled-password --gecos '' nodeuser
USER nodeuser

WORKDIR /app

COPY --chown=nodeuser:nodeuser echonet-frontend/package*.json ./ 

RUN npm config set script-shell bash && \
    npm cache clean --force && \
    npm install

COPY --chown=nodeuser:nodeuser echonet-frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev"]
