FROM python:3.11-slim

WORKDIR /app

# Copiar solo los requirements
COPY echonet_backend/requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]