# Generated by Django 5.2.1 on 2025-05-26 08:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_music_attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_id', models.CharField(blank=True, max_length=255, null=True)),
                ('embed_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_music_attachments', to='chat.conversation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_music_attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_music_attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_id', models.CharField(blank=True, max_length=255, null=True)),
                ('embed_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_music_attachments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_music_attachments', to='post.post')),
            ],
        ),
        migrations.CreateModel(
            name='User_fav_albums',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('album_id', models.CharField(blank=True, max_length=255, null=True)),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('album_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('album_image', models.URLField(blank=True, null=True)),
                ('album_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spotify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fav_albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_fav_artists',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artist_id', models.CharField(blank=True, max_length=255, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=255, null=True)),
                ('artist_image', models.URLField(blank=True, null=True)),
                ('artist_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spotify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fav_artists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_fav_tracks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('track_id', models.CharField(blank=True, max_length=255, null=True)),
                ('track_name', models.CharField(blank=True, max_length=255, null=True)),
                ('track_artist', models.CharField(blank=True, max_length=255, null=True)),
                ('track_image', models.URLField(blank=True, null=True)),
                ('track_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spotify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fav_tracks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
