# Generated by Django 5.2.1 on 2025-05-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_fav_albums',
            old_name='spotify_user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='user_fav_artists',
            old_name='spotify_user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='user_fav_tracks',
            old_name='spotify_user',
            new_name='created_by',
        ),
    ]
