# Generated by Django 5.2.1 on 2025-05-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_rename_spotify_user_user_fav_albums_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_music_attachment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post_music_attachment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Chat_music_attachment',
        ),
        migrations.DeleteModel(
            name='Post_music_attachment',
        ),
    ]
