# Generated by Django 5.2.1 on 2025-05-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_post_music_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_music_attachment',
        ),
    ]
