# Generated by Django 5.2.1 on 2025-05-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_delete_post_music_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_fav_artists',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user_fav_tracks',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='User_fav_albums',
        ),
        migrations.DeleteModel(
            name='User_fav_artists',
        ),
        migrations.DeleteModel(
            name='User_fav_tracks',
        ),
    ]
