# Generated by Django 5.2.1 on 2025-05-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='track_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
