# Generated by Django 5.2.1 on 2025-05-29 07:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_musicattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicAttachment',
            new_name='PostMusicAttachment',
        ),
    ]
