# Generated by Django 5.2.1 on 2025-05-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_musicattachment_postmusicattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmusicattachment',
            name='embed_html',
        ),
    ]
