# Generated by Django 5.2.1 on 2025-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_postmusicattachment_embed_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmusicattachment',
            name='track_id',
            field=models.CharField(blank=True, default=2, max_length=255),
            preserve_default=False,
        ),
    ]
