# Generated by Django 5.2.1 on 2025-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_postmusicattachment_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmusicattachment',
            name='track_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
