# Generated by Django 5.2.1 on 2025-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_postmusicattachment_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmusicattachment',
            name='track_id',
            field=models.CharField(max_length=255),
        ),
    ]
