# Generated by Django 5.2.1 on 2025-05-30 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_postmusicattachment_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmusicattachment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_attachments', to='post.post'),
        ),
    ]
