# Generated by Django 5.2.1 on 2025-05-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_spotifyuserfavalbums_spotifyuserfavartists_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotifyUserFavAlbums',
            new_name='SpotifyUser_Fav_Albums',
        ),
        migrations.RenameModel(
            old_name='SpotifyUserFavArtists',
            new_name='SpotifyUser_Fav_Artists',
        ),
        migrations.RenameModel(
            old_name='SpotifyUserFavTracks',
            new_name='SpotifyUser_Fav_Tracks',
        ),
    ]
