# Generated by Django 5.2.1 on 2025-05-30 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_spotifyuserfavalbums_spotifyuser_fav_albums_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners'),
        ),
        migrations.AddField(
            model_name='spotifyuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyuser_fav_albums',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spotifyuser_fav_artists',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spotifyuser_fav_tracks',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
